import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/dashboard/app-sidebar'
import { Separator } from '@/components/ui/separator'
import { auth } from '@/auth'
import GlobalLoadingClient from '@/components/shared/global-client-loader'
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'The Motorcycle',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang='en' className='m-0 p-0 h-full' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0 h-full`}
      >
        <Providers>
          <Toaster
            position='top-center'
            toastOptions={{
              duration: 3000,
            }}
          />
          <GlobalLoadingClient />
          {session?.user ? (
            <div>
              <SidebarProvider>
                <AppSidebar />
                <SidebarInset>
                  <header className='flex h-16 shrink-0 items-center gap-2 border-b px-4'>
                    <SidebarTrigger className='-ml-1' />
                    <Separator
                      orientation='vertical'
                      className='mr-2 data-[orientation=vertical]:h-4'
                    />
                    {/* <Breadcrumb>
            <BreadcrumbList>
              <BreadcrumbItem className="hidden md:block">
                <BreadcrumbLink href="#">
                  Building Your Application
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator className="hidden md:block" />
              <BreadcrumbItem>
                <BreadcrumbPage>Data Fetching</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb> */}
                  </header>
                  <div className='px-2 py-5 sm:px-5 sm:py-5'>{children}</div>
                </SidebarInset>
              </SidebarProvider>
            </div>
          ) : (
            <div className=''>{children}</div>
          )}
        </Providers>
      </body>
    </html>
  )
}
